### PR TITLE
Initial history bulk loader file.

### PR DESCRIPTION
**Pull request by Fongja37**
Initial history bulk loader: returns 1D numpy array from specified Open Weather Map History bulk csv data file. Array contains data from csv for given feature, timeframe, and time step.

### CODE REVIEW

**Comment by Fongja37** [comment]
We will need to comment out the example usage. Left in for demonstration purposes through the team.

**Comment by dunnlu** [comment]
1) Do you know if there are any anomalies when it comes to daylight savings? This is the only potential issue I saw. 

2) We need to decide as a group what features to consider, for example our one_call_api_loader code does not account for:

"weather": [
        {
          "id": 800,
          "main": "Clear",
          "description": "clear sky",
          "icon": "01d"
        }

Our thought process was that it would be hard to compute loss on these features. If we wanted to do something similar to the data in our CS 434 HW where "country" was made into a binary feature for each country, but for weather description (for example) then we could, but we would need to decide on that.

Other than that it looks good to me, with the input and outputs.

**Review by dunnlu — APPROVED** [review]
Limiting the requested feature can be handled in the loss calculator, and since this is a private library to only be used by loss calculator, I think it is ready to merge.

**Review by danilkryuchkov — APPROVED** [review]

**Review by danilkryuchkov — APPROVED** [review]

**Review by danilkryuchkov — APPROVED** [review]

**Review by kryuchkd — APPROVED** [review]

**Comment by kryuchkd** [comment]
don't know how my personal GitHub became a part of this, maybe I forgot to switch at some point

**Pull request merged**
